#  thetano usage

In [2]:
import numpy as np
import theano.tensor as tt
from theano import function

In [6]:
x = tt.dscalar("x")
y = tt.dscalar("y")
z = x + y
f = function([x,y],z)

In [7]:
f(2,3)

array(5.)

In [8]:
a = tt.vector("a")
b = tt.vector("b")
out = a**2 + b ** 2 + 2*a*b
f = function([a,b],out)

In [10]:
f([1,2],[2,3])

array([ 9., 25.])

In [15]:
a,b = tt.vectors("a","b")
out = a**2 + b ** 2 + 2*a*b
f = function([a,b],out)

In [16]:
f([1,2],[2,3])

array([ 9., 25.])

# logistic function

In [13]:
x = tt.dmatrix("x")
s = 1/ (1 + tt.exp(-x))
logistic = function([x],s)

In [14]:
logistic([[0,1],[-1,-2]])

array([[0.5       , 0.73105858],
       [0.26894142, 0.11920292]])