#  thetano usage

In [4]:
import numpy as np
import theano.tensor as tt
import theano
from theano import function

In [6]:
x = tt.dscalar("x")
y = tt.dscalar("y")
z = x + y
f = function([x,y],z)

In [7]:
f(2,3)

array(5.)

In [8]:
a = tt.vector("a")
b = tt.vector("b")
out = a**2 + b ** 2 + 2*a*b
f = function([a,b],out)

In [10]:
f([1,2],[2,3])

array([ 9., 25.])

In [15]:
a,b = tt.vectors("a","b")
out = a**2 + b ** 2 + 2*a*b
f = function([a,b],out)

In [16]:
f([1,2],[2,3])

array([ 9., 25.])

# logistic function

In [13]:
x = tt.dmatrix("x")
s = 1/ (1 + tt.exp(-x))
logistic = function([x],s)

In [14]:
logistic([[0,1],[-1,-2]])

array([[0.5       , 0.73105858],
       [0.26894142, 0.11920292]])

#  switch

In [12]:
a,b = tt.scalars("a","b")
z = tt.switch(tt.ge(a,b),1,2)

f_switch = theano.function([a, b],z)
f_switch(1,2)

array(2, dtype=int8)

In [20]:
a,b = tt.scalars("a","b")
z = tt.stack([a,1],[b])
f = theano.function([a,b],z)

UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 1 is not part of the computational graph needed to compute the outputs: b.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.

array([0., 1.])